version: "3"
services:
  mcp-server:
    container_name: mcp-server
    hostname: mcp-server
    image: tl-vault:latest
#    entrypoint: /usr/bin/sleep
#    command: "9999999"
    ports:
    - 8800:8200
#     network_mode: "host"
    volumes:
    - ./configs/mcp-server.hcl:/etc/vault.d/server.hcl:ro
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./gpg:/opt/gpg:rw
    - ./raft/mcp-server:/raft:rw
  server1:
    container_name: server1
    hostname: server1
    image: tl-vault:latest
#    entrypoint: /usr/bin/sleep
#    command: "9999999"
    ports:
    - 8400:8200
#     network_mode: "host"
    volumes:
    - ./configs/server1.hcl:/etc/vault.d/server.hcl:ro
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./vault-agent-exec:/init/vault-agent-exec:rw
    - ./gpg:/opt/gpg:rw
    - ./raft/server1:/raft:rw
    - ./configs/init1-config:/init:rw
    - ./tls/vault1-key.pem:/tls/key.pem:ro
    - ./tls/vault1-cert.pem:/tls/cert.pem:ro
    - ./tls/vault-ca.pem:/tls/ca.pem:ro
  server2:
    container_name: server2
    hostname: server2
    image: tl-vault:latest
#    entrypoint: /usr/bin/sleep
#    command: "9999999"
    ports:
    - 8200:8200
    # network_mode: "host"
    volumes:
    - ./configs/server2.hcl:/etc/vault.d/server.hcl:ro
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./raft/server2:/raft:rw
    - ./configs/init2-config:/init:rw
    - ./tls/vault2-key.pem:/tls/key.pem:ro
    - ./tls/vault2-cert.pem:/tls/cert.pem:ro
    - ./tls/vault-ca.pem:/tls/ca.pem:ro
  server3:
    container_name: server3
    hostname: server3
    image: tl-vault:latest
#    entrypoint: /usr/bin/sleep
#    command: "9999999"
#     network_mode: "host"
    ports:
    - 8500:8200
    volumes:
    - ./configs/server3.hcl:/etc/vault.d/server.hcl:ro
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./gpg:/opt/gpg:rw
    - ./raft/server3:/raft:rw
    - ./configs/init3-config:/init:rw
    - ./tls/vault3-key.pem:/tls/key.pem:ro
    - ./tls/vault3-cert.pem:/tls/cert.pem:ro
    - ./tls/vault-ca.pem:/tls/ca.pem:ro
  linux:
    container_name: linux
    hostname: linux
    image: tl-ubuntu:latest
    entrypoint: ["/bin/bash"]
    command: ["-c", "while true; do sleep 30; done"]

#    entrypoint: /usr/bin/sleep
#    command: "9999999"
#     network_mode: "host"
    ports:
    - 8700:8200
    volumes:
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./vault-agent-exec:/init/vault-agent-exec:rw
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http https://server3:8200
    environment:
      - NGROK_AUTHTOKEN=2ih5uiOaNBVclpL65sxPHLdOlEc_4dxZFzRDP6B1VAfxP5wF8
    depends_on:
      - server3